## Import numpy dependency

In [1]:
import numpy as np

## 1D Array

In [2]:
a = np.array([1,2,3,4,5]); a

array([1, 2, 3, 4, 5])

## MuiltiDimensional Array

In [3]:
b = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]]); b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array creation

In [4]:
#create an array with zeros:
c = np.zeros((2,2,2));print(c)

#create an array with ones:
d = np.ones(2); print(d)

#create an empty array of 4:
x = np.empty(4); print(x)

# create a full array
z = np.full((2,2), 7); print(z)

#aranage of an array of length 4:
y = np.arange(4);print(y)
z = np.arange(4,8,1); print(z)

#Using linspace
p = np.linspace(1,10, num=4);print(p)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[1. 1.]
[1.28822975e-231 3.10503643e+231 2.12973439e-314 2.78134232e-309]
[[7 7]
 [7 7]]
[0 1 2 3]
[4 5 6 7]
[ 1.  4.  7. 10.]


## Specifying DataType

In [5]:
data = np.arange(4, dtype = np.int64); print(type(data)); print(data)

<class 'numpy.ndarray'>
[0 1 2 3]


## Adding, removing and sorting an array

In [6]:
#Sorting of an array:
x = np.array([2,5,7,4,1,3,5]);print("unsorted array -",x)
print("sorted array -",np.sort(x))

#concatenate the two arrays:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print("concatenating of two arrays -", np.concatenate((a,b)))

#concatenating of multiDimensional array's
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print("concatenating of two arrays -", np.concatenate((x,y), axis=0))

unsorted array - [2 5 7 4 1 3 5]
sorted array - [1 2 3 4 5 5 7]
concatenating of two arrays - [1 2 3 4 5 6 7 8]
concatenating of two arrays - [[1 2]
 [3 4]
 [5 6]]


## Shape and Size of an array

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3)

In [7]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

# ndarray.ndim will tell you the number of axes, or dimensions, of the array.
print(array_example.ndim)

# ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.
print(array_example.size)

#ndarray.shape
print(array_example.shape)


3
24
(3, 2, 4)


## Reshape an Array

In [8]:
array = np.arange(6); print("given array =", array)
reshaped_array = array.reshape(3,2); print("reshaped array =", reshaped_array)
np.reshape(array, newshape=(1, 6), order='c')

given array = [0 1 2 3 4 5]
reshaped array = [[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

## indexing and slicing

In [9]:
data = np.array([1, 2, 3]); data[0:2]
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<5])# return values

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

five_up = (a>5)# return boolean
print(five_up)

c = a[(a>2) & (a<8)]
print(c)

b = np.nonzero(a < 5);print(b)

# zip of an array
ziping = list(zip(b[0], b[1]))

for coord in ziping:
    print(coord)

[1 2 3 4]
[ 2  4  6  8 10 12]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[3 4 5 6 7]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(0, 0)
(0, 1)
(0, 2)
(0, 3)


## create an array from existing array

In [27]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a2 = a[3:8]
print(a2)

# stack two existing arrays
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

# Vertical stack
print(np.vstack((a1,a2)))

# Horizantal Stack

print(np.hstack((a1,a2)))

# You can split an array into several smaller arrays using hsplit. 
#You can specify either the number of equally shaped arrays to return or the columns after which the division should occur
a3 = np.arange(24).reshape(4,6);print(a3)

# Split into three equally shaped arrays
a4 = np.hsplit(a3, 3);print(a4)

#using views
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]);print(a[1,:])
b = a[1,:]
b[0] = 99
print(a)

[4 5 6 7 8]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]
[5 6 7 8]
[[ 1  2  3  4]
 [99  6  7  8]
 [ 9 10 11 12]]


## convert a 1D array into a 2D array (how to add a new axis to an array)

In [11]:
a = np.array([1,2,3,4,5,6])
a.ndim

# convert a 1D array to a row vector by inserting an axis along the first dimension:
row_vector = a[np.newaxis,:]; print(row_vector); print(row_vector.ndim)

column_vector = row_vector[:, np.newaxis]; print(column_vector.ndim)

# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1); print(b.ndim); print(b)
c = np.expand_dims(a, axis=0); print(c.ndim); print(c)

[[1 2 3 4 5 6]]
2
3
2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2
[[1 2 3 4 5 6]]


## Creating Matrices

In [40]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data[0:3,1];data.max(); data.min(); data.sum()

data.max(axis=0); data.max(axis=1)


array([2, 4, 6])